### ISSUE TITLE
LLVM version

### ISSUE THREAD

**Issue by d-ned** [hc825b/kint#1]
Hello, what's the most suitable version of _LLVM_ to install in order to compile _kint_?

**Comment by hc825b** [comment]
The original repository at https://github.com/CRYPTOlab/kint should work with LLVM 3.1 or 3.2.

For our `master` branch, we compile and ran the tests with LLVM 3.2, and it went well as far as I recall. Note that you also need Clang 3.2 to translate C code to LLVM IR for their tests.

Our `llvm-3.8.0` and `llvm-3.9.1` branches were experimental, and I don't remember if we successfully compiled it or not. Based on my commit messages, I think `llvm-3.9.1` is more likely to work, and you will need both LLVM 3.9.1 and Clang 3.9.1.

**Comment by d-ned** [comment]
Thanks.
